#!/usr/bin/python3
# SPDX-FileCopyright Text: 2023 Kento Tsutsui
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 1

try:
    F = int(input())
    for line in sys.stdin:
         ans += tonum(line)
    print(ans)
      
except:
    print("Error")
