#!/usr/bin/python3
# SPDX-FileCopyright Text: 2023 Kento Tsutsui
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)
